import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/dev/navbar";
import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/auth";
import SessionProvider from "@/components/store/session-provider";
import GenralProvider from "@/components/store/genral-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden px-3 md:p-0`}
      >
        <SessionProvider session={session}>
          <Navbar />
          <div className="mx-auto w-full max-w-5xl ">{children}</div>
          <Toaster />
          <GenralProvider />
        </SessionProvider>
      </body>
    </html>
  );
}
